### ISSUE TITLE
how download your's software

### ISSUE THREAD

**Issue by yosaf12345** [arysoftplay/-rySubRipper#1]
i need help

**Comment by arysoftplay** [comment]
Hi Yosaf,

You have to go into the releases page at https://github.com/arysoftplay/-rySubRipper/releases

Download the last release (currently @rySubRipper.v1.3.rar) by clicking on the link.

![image](https://user-images.githubusercontent.com/80472189/152012615-71db7d91-8422-4eb3-9d47-9be7592374f5.png)

You have to extract the contents in a folder and run the @rySubRipper.jar.

I recommend you to read the user guide (@rySubRipper_Doc.pdf) first.

You will need to install java and VLC in your computer in order to use the app.

**Comment by yosaf12345** [comment]
i have vlc and java please help me

**Comment by arysoftplay** [comment]
Hi Yosaf,
What is the problem?
Have you read the document?

**Comment by yosaf12345** [comment]
Yes but I did not understand...

**Comment by arysoftplay** [comment]
Can you explain your problem?
Did you extract the files in a folder?
Did you run the @rySubRipper.jar?
Does the application open?
Do you have an error?
Did you follow the steps in chapters 3 and 4?

**Comment by yosaf12345** [comment]
ERROR: Parameter background_mode missing on the database
