### ISSUE TITLE
Subtitles in Israeli shows 

### ISSUE THREAD

**Issue by Flafkas** [arysoftplay/-rySubRipper#3]
Hello! 

I do not know exactly where to contact you so I'll do it here. I've recently been trying to find subtitles for the show "Ha-Pijamot" and I was very happy to see that you have made a single EP already with English subtitles. I am going to check out your software and hopefully make it work on other EPS as well.

I wanted to ask if you got any more eps with subtitles or if you can give a detailed information regarding the software you're working on and how to use it properly. Thank you!

**Comment by arysoftplay** [comment]
Hi Flafkas,
You can download the current version of the software and read @rySubRipper_Doc.pdf. I think that is detailed enough but if you have any questions do not hesitate to contact me.

Concerning Ha-Pijamot, I didn't do any more episodes because it was a nightmare. Different fonts, bad image quality and lot of almost white background made very hard to work with the OCR. If you want to work on more episodes I recommend to use it in manual mode (no OCR).
